import type { LucideIcon } from "lucide-react";
import {
  Building2,
  Stethoscope,
  UtensilsCrossed,
  Truck,
  ShoppingBag,
  Factory,
  Home,
  Briefcase,
  Cpu,
  Globe,
  Hammer,
  HardHat,
  Wrench,
  Tractor,
  Leaf,
  Smile,
  HandCoins,
  Baby,
  Pizza,
  Hotel,
  Coffee,
  Car,
  Bus,
  Plane,
  Scissors,
  Dumbbell,
  Store,
  ShoppingCart,
  Package,
  Boxes,
  Cog,
  Building,
  Banknote,
  Scale,
  Calculator,
  Laptop,
  CreditCard,
  Receipt,
  TrendingUp,
  LineChart,
  Megaphone,
  Sparkles,
} from "lucide-react";

export type Service = {
  slug: string;
  title: string;
  icon: LucideIcon;
  tagline: string;
  description: string;
  bullets: string[];
  highlight: string;
};

export type Industry = {
  slug: string;
  label: string;
  icon: LucideIcon;
  hero: string;
  intro: string;
  services: Service[];
};

const make = (
  slug: string,
  title: string,
  icon: LucideIcon,
  tagline: string,
  description: string,
  bullets: string[],
  highlight: string,
): Service => ({ slug, title, icon, tagline, description, bullets, highlight });

export const INDUSTRIES: Industry[] = [
  {
    slug: "construction",
    label: "Construction",
    icon: Building2,
    hero: "Capital that breaks ground.",
    intro:
      "From downtown Austin mid-rise builds to Hill Country custom homes and Domain mixed-use projects, we structure financing that keeps Central Texas crews moving across one of the most active construction markets in the country.",
    services: [
      make(
        "commercial-construction-loan",
        "Commercial Construction Loan",
        Hammer,
        "Ground-up & renovation projects",
        "Multi-draw financing aligned to your Austin construction schedule with interest-only periods during the build phase.",
        ["Up to 80% LTC", "12-36 month terms", "Convertible to permanent financing"],
        "Funding $250K-$25M",
      ),
      make(
        "equipment-financing",
        "Construction Equipment Financing",
        HardHat,
        "Excavators, cranes, loaders",
        "Finance new or used heavy equipment with the equipment itself serving as collateral, preserving working capital for jobs.",
        ["100% financing available", "Section 179 eligible", "Approvals in 24-48 hours"],
        "Rates from 6.99%",
      ),
      make(
        "equipment-loans",
        "Equipment Loans",
        Wrench,
        "Own outright after the final payment",
        "Fixed-rate loans designed for contractors who want to build equity in their fleet without leasing handoffs.",
        ["Fixed monthly payments", "Terms 2-7 years", "Tax deduction advantages"],
        "$10K-$5M",
      ),
      make(
        "agriculture-equipment-financing",
        "Agriculture Equipment Financing",
        Tractor,
        "Tractors, implements & ranch equipment",
        "Seasonal-friendly structures tailored to Hill Country ranch and farm cash flow, with deferred payments aligned to grazing and harvest cycles.",
        ["Seasonal payment options", "New & used equipment", "Trade-in friendly"],
        "Same-week funding",
      ),
      make(
        "landscaping-equipment-financing",
        "Landscaping Equipment Financing",
        Leaf,
        "Mowers, trucks and trailers",
        "Build out your Austin landscaping fleet with financing built for year-round Texas operations — HOA-heavy suburbs keep crews running 12 months a year.",
        ["Bundle multiple units", "Skip-payment options", "Soft credit pulls"],
        "Pre-qualify in minutes",
      ),
    ],
  },
  {
    slug: "healthcare",
    label: "Healthcare",
    icon: Stethoscope,
    hero: "Funding for those who care.",
    intro:
      "Specialized lending for Austin medical, dental, aesthetics and childcare practices: from buy-ins to build-outs and the latest imaging, laser and body-contouring equipment serving the Westlake, Domain, Mueller and Cedar Park markets.",
    services: [
      make(
        "medical-practice-loans",
        "Medical Practice Loans",
        Stethoscope,
        "Clinics & physician groups",
        "Acquisition, partner buy-in, expansion and working capital tailored to insurance reimbursement timing — sized for Austin's dense pediatric, dermatology and primary-care market.",
        ["Up to 100% project financing", "Terms up to 10 years", "Deferred payment options"],
        "$50K-$7M",
      ),
      make(
        "dental-practice-loans",
        "Dental Practice Loans",
        Smile,
        "Equipment, expansion & acquisition",
        "Finance chairs, CBCT imaging, build-outs or a full practice purchase with structures designed for Westlake, Domain, Round Rock and Cedar Park DSOs and solo practices.",
        ["Chairs, imaging & software", "Practice acquisition", "Refinance existing debt"],
        "Rates from 7.25%",
      ),
      make(
        "sba-loan-for-daycare",
        "SBA Loan for Daycare",
        Baby,
        "Childcare facility financing",
        "SBA 7(a) and 504 loans for licensed Travis and Williamson County childcare operators — real estate, renovation, equipment and working capital in one package.",
        ["10% down on real estate", "25-year amortization", "Low fixed rates"],
        "Up to $5M",
      ),
      make(
        "professional-services",
        "Allied Professional Loans",
        HandCoins,
        "Aesthetics, therapy, veterinary",
        "Capital for the wider care economy — medical aesthetics, veterinary expansion, physical therapy clinics, behavioral health and Austin's growing wellness sector.",
        ["No collateral options", "Bridge & permanent financing", "Cash-out refinance"],
        "48-hour approvals",
      ),
    ],
  },
  {
    slug: "restaurants",
    label: "Restaurants & Hospitality",
    icon: UtensilsCrossed,
    hero: "Fuel the next service.",
    intro:
      "Working capital and equipment financing for Austin restaurants, BBQ joints, food trucks, breweries and hospitality — from SoCo to East Austin to the Domain — sized to the realities of Texas hospitality margins.",
    services: [
      make(
        "restaurant-loans",
        "Restaurant Loans",
        UtensilsCrossed,
        "Fit-out, expansion & equipment",
        "Open the second location, refresh the dining room or weather a slow season with capital structured for Austin hospitality cash flow.",
        ["Daily, weekly or monthly payments", "Same-day approvals", "No equity required"],
        "$25K-$2M",
      ),
      make(
        "food-truck-financing",
        "Food Truck Financing",
        Pizza,
        "Mobile food business funding",
        "Finance the truck, the build-out and the commissary kitchen — Austin pioneered the modern food-truck scene and our lenders know it cold.",
        ["New & used trucks", "100% financing", "Startup-friendly"],
        "Approvals in 24 hours",
      ),
      make(
        "hotel-loans",
        "Hotel Loans",
        Hotel,
        "Acquisition & PIP renovation",
        "Capital for flagged and independent properties across Downtown Austin, the Domain, SoCo and Hill Country resort markets.",
        ["SBA 7(a) & 504", "Bridge to perm", "Up to 90% LTV"],
        "$500K-$25M",
      ),
      make(
        "cafe-financing",
        "Café & Coffee Shop Financing",
        Coffee,
        "Espresso bars to roasteries",
        "Equipment-heavy financing for cafes, roasters and specialty coffee concepts — including the East Austin third-wave roastery cluster.",
        ["Equipment + working capital", "Soft credit pre-qual", "No prepayment penalty"],
        "From $15K",
      ),
    ],
  },
  {
    slug: "transportation",
    label: "Transportation & Logistics",
    icon: Truck,
    hero: "Keep the fleet rolling.",
    intro:
      "From SH-130 freight forwarders and Samsung/Tesla supplier-chain operators to last-mile e-commerce delivery serving the Austin metro: trucks, trailers, repair bays and the working capital that holds Central Texas logistics together.",
    services: [
      make(
        "trucking-business-loans",
        "Trucking Business Loans",
        Truck,
        "Owner-operators to fleet expansion",
        "Capital to add tractors, cover insurance down payments, fuel up and bridge slow-pay receivables — built for I-35, SH-130 and the Texas Triangle freight corridor.",
        ["DOT-friendly underwriting", "Factoring + term combos", "Fuel & maintenance reserves"],
        "Funded in 24 hours",
      ),
      make(
        "auto-repair-shop-financing",
        "Auto Repair Shop Financing",
        Wrench,
        "Bays, lifts and diagnostics",
        "Equipment and real estate financing for Austin independent shops, collision centers and quick-lube operators.",
        ["Lifts, alignment & ADAS", "Real estate purchase", "Up to 7-year terms"],
        "Rates from 7.5%",
      ),
      make(
        "fleet-vehicle-financing",
        "Fleet & Vehicle Financing",
        Car,
        "Light-duty to heavy fleets",
        "Single units or full fleets: sedans, sprinter vans, box trucks and specialty vehicles with predictable payments — sized for Austin's services, construction and tech-delivery economies.",
        ["TRAC leases & loans", "Upfit financing included", "Bundle multiple vehicles"],
        "100% financing",
      ),
      make(
        "logistics-working-capital",
        "Logistics Working Capital",
        Bus,
        "3PL and freight forwarders",
        "Lines of credit and revenue-based financing to scale SH-130 corridor logistics operations during semiconductor supply-chain cycles.",
        ["Same-day draws", "Lines up to $2M", "Revolving structures"],
        "No collateral required",
      ),
    ],
  },
  {
    slug: "retail",
    label: "Retail & Lifestyle",
    icon: ShoppingBag,
    hero: "Stock more. Sell more.",
    intro:
      "Inventory financing, build-outs and working capital for Austin storefronts, salons, gyms and lifestyle retail concepts — Domain flagships to SoCo indies and East Austin newcomers.",
    services: [
      make(
        "retail-business-loans",
        "Retail Business Loans",
        ShoppingBag,
        "Inventory & storefront capital",
        "Stock up for the season, open a second location, or refresh your Austin storefront with capital sized to retail cash flow cycles and SXSW/ACL spikes.",
        ["Seasonal payment structures", "Inventory financing", "POS-integrated underwriting"],
        "$15K-$1M",
      ),
      make(
        "salon-business-loans",
        "Salon & Med-Spa Loans",
        Scissors,
        "Beauty, wellness & medical aesthetics",
        "Chair rentals, suite build-outs, product inventory, lasers and injectables — capital built for Austin's growing aesthetics market.",
        ["Equipment & build-out", "Marketing & inventory", "Med-spa & aesthetics"],
        "Quick pre-qual",
      ),
      make(
        "loan-for-gym-business",
        "Loan for Gym Business",
        Dumbbell,
        "Equipment & build-out",
        "Outfit the floor, expand into recovery and group fitness, or refinance higher-rate equipment leases — Austin is one of the most active fitness markets in the country.",
        ["Cardio + strength bundles", "Recovery & spa add-ons", "Refinance options"],
        "Up to $500K",
      ),
      make(
        "boutique-storefront-funding",
        "Boutique & Storefront Funding",
        Store,
        "Independent retailers",
        "Pop-ups to permanent locations: working capital and short-term financing for indie brands and boutiques in SoCo, East Austin and the Domain.",
        ["Short-term + revolving", "No equity dilution", "Approvals in 24 hours"],
        "Soft credit pull",
      ),
    ],
  },
  {
    slug: "manufacturing",
    label: "Manufacturing",
    icon: Factory,
    hero: "Capital that scales the line.",
    intro:
      "Heavy equipment, working capital and receivables financing for manufacturers, fabricators and producers across the SH-130 industrial corridor and the Samsung/Tesla supplier base in Central Texas.",
    services: [
      make(
        "manufacturing-equipment-financing",
        "Manufacturing Equipment Financing",
        Cog,
        "CNC, fabrication & production lines",
        "Finance individual machines or entire production cells with structures that align to ROI timelines, including soft costs.",
        ["New & used equipment", "Soft costs included", "Step payment options"],
        "Up to $10M",
      ),
      make(
        "working-capital-loans",
        "Working Capital Loans",
        Banknote,
        "Bridge purchase orders & payroll",
        "Cover raw material spikes, fund large purchase orders, or bridge customer payment terms without giving up equity.",
        ["Lines up to $5M", "Same-day draws", "Revolving structures"],
        "Funded same week",
      ),
      make(
        "invoice-factoring",
        "Invoice Factoring",
        Receipt,
        "Turn AR into cash today",
        "Sell your invoices for immediate liquidity: non-recourse and recourse options popular with Texas semiconductor suppliers and freight-tied manufacturers.",
        ["Advance rates up to 95%", "Non-recourse available", "No long-term contracts"],
        "24-hour funding",
      ),
      make(
        "accounts-receivable-financing",
        "Accounts Receivable Financing",
        Boxes,
        "Lines secured by your AR",
        "A revolving facility that grows with your receivables, cheaper than factoring when volume is consistent.",
        ["Up to 90% AR advance", "Maintain customer relationships", "Reporting-friendly"],
        "Lines $250K-$20M",
      ),
    ],
  },
  {
    slug: "real-estate",
    label: "Real Estate",
    icon: Home,
    hero: "Build the Texas portfolio.",
    intro:
      "Acquisition, construction and bridge financing for Central Texas investors, owner-operators and commercial real estate professionals — one of the most actively traded CRE markets in the United States.",
    services: [
      make(
        "commercial-real-estate-loans",
        "Commercial Real Estate Loans",
        Building,
        "Owner-occupied & investment",
        "Long-term fixed-rate financing for Austin retail, office, industrial and multifamily properties — SBA 504 and conventional CRE for Downtown, Domain, East Austin and the SH-130 corridor.",
        ["Up to 25-year amortization", "90% LTV on owner-occupied", "Cash-out refinance"],
        "$250K-$25M",
      ),
      make(
        "business-acquisition-loans",
        "Business Acquisition Loans",
        Briefcase,
        "Buy the building & the business",
        "Combined acquisition packages that finance the operating business and the real estate it sits on in one closing — common in Williamson County succession deals.",
        ["10% down with SBA", "Goodwill financing", "Earn-out friendly"],
        "Close in 45-60 days",
      ),
      make(
        "construction-to-perm",
        "Construction-to-Permanent",
        Hammer,
        "Single-close construction",
        "Avoid two closings with a single-close construction-to-permanent loan that converts automatically at certificate of occupancy.",
        ["Single closing", "Lock perm rate early", "Interest-only during build"],
        "Up to $15M",
      ),
      make(
        "bridge-financing",
        "Bridge Financing",
        TrendingUp,
        "Speed when you need it",
        "Short-term bridge capital for value-add Austin acquisitions, reposition plays and 1031 exchanges into Texas from higher-tax states.",
        ["6-24 month terms", "Interest-only", "Close in 2 weeks"],
        "Up to 75% LTV",
      ),
    ],
  },
  {
    slug: "professional-services",
    label: "Professional Services",
    icon: Briefcase,
    hero: "Capital for the firm.",
    intro:
      "Tailored financing for Austin law firms, accounting practices, consulting groups, wealth advisors and the family offices that have been relocating to Texas at record pace.",
    services: [
      make(
        "professional-services-loans",
        "Professional Services Loans",
        Briefcase,
        "Law, accounting & consulting",
        "Partner buy-ins, lateral hires, technology and office build-outs financed around partner draw cycles.",
        ["Unsecured options to $500K", "Partner buy-in financing", "Tech & build-out included"],
        "Soft pull pre-qual",
      ),
      make(
        "business-line-of-credit",
        "Business Line of Credit",
        CreditCard,
        "Draw what you need, when you need it",
        "Revolving capital that's there when AR slows or a new matter ramps up. Only pay interest on what you draw.",
        ["Lines $25K-$500K", "Same-day draws", "Pay interest only on used balance"],
        "Rates from 8.99%",
      ),
      make(
        "unsecured-business-loans",
        "Unsecured Business Loans",
        Scale,
        "No collateral, no liens",
        "Cash-flow-based underwriting for established firms with strong revenue. No UCC blanket liens or personal collateral.",
        ["Funded in 1-3 days", "Terms 1-5 years", "No equity required"],
        "Up to $500K",
      ),
      make(
        "loan-broker-services",
        "Business & Commercial Loan Brokering",
        Calculator,
        "We shop our lender network for you",
        "Access 75+ vetted lenders through one application. Texas-licensed specialists who know the Central Texas market.",
        ["75+ lender network", "One application", "We negotiate on your behalf"],
        "No fee until close",
      ),
    ],
  },
  {
    slug: "technology",
    label: "Technology",
    icon: Cpu,
    hero: "Non-dilutive growth capital.",
    intro:
      "Revenue-based financing, lines of credit and equipment leases for the Austin tech cluster — Domain SaaS, East Austin creators, downtown VC-backed startups and the broader 'Silicon Hills' ecosystem.",
    services: [
      make(
        "revenue-based-financing",
        "Revenue-Based Financing",
        LineChart,
        "Pay as you earn",
        "Capital priced as a fixed multiple, repaid as a percentage of monthly revenue. No equity, no fixed installments.",
        ["No equity dilution", "No personal guarantee*", "Flexible repayment"],
        "$50K-$5M",
      ),
      make(
        "sba-loan-for-franchise",
        "SBA Loan for Tech & Franchise",
        Sparkles,
        "SBA 7(a) for tech-enabled franchises",
        "Long-term fixed financing for franchise owners and tech-enabled service businesses. Leverage SBA terms for scale.",
        ["Up to 10-year terms", "10% down typical", "Low fixed rates"],
        "Up to $5M",
      ),
      make(
        "tech-equipment-leasing",
        "Tech Equipment Leasing",
        Laptop,
        "Servers, devices & cloud",
        "Lease laptops, servers and AV equipment with built-in refresh cycles. Operational expense treatment.",
        ["24-60 month terms", "Refresh built in", "Bundled service"],
        "From $10K",
      ),
      make(
        "growth-marketing-capital",
        "Growth & Marketing Capital",
        Megaphone,
        "Fund the acquisition flywheel",
        "Working capital sized for ad spend and growth campaigns with payback structured to CAC payback periods.",
        ["Up to $2M", "Flexible draws", "Performance-aligned"],
        "Funded in 48 hours",
      ),
    ],
  },
  {
    slug: "e-commerce",
    label: "E-Commerce",
    icon: Globe,
    hero: "Capital that ships.",
    intro:
      "Inventory financing, ad spend capital and working capital for Austin DTC brands, marketplace sellers and omnichannel retailers shipping out of Central Texas fulfillment centers.",
    services: [
      make(
        "ecommerce-business-funding",
        "E-Commerce Business Funding",
        Globe,
        "Inventory & ad spend capital",
        "Capital sized to your AOV, repeat rate and marketing payback, purpose-built for Shopify, Amazon and DTC brands.",
        ["Integrates with Shopify & Amazon", "Daily or weekly remittance", "Scales with revenue"],
        "$25K-$3M",
      ),
      make(
        "inventory-financing",
        "Inventory Financing",
        Package,
        "Land the next PO",
        "Finance inbound inventory with terms aligned to your sell-through cycle, perfect for seasonal SKUs and BFCM ramps — sized for Central Texas 3PL operators.",
        ["Up to 80% of cost", "Pay as you sell", "Multi-SKU support"],
        "Pre-approve in 24 hours",
      ),
      make(
        "merchant-cash-advance",
        "Merchant Cash Advance",
        ShoppingCart,
        "Fast capital against future sales",
        "An advance against future card and platform sales, funded fast and repaid as a small percentage of daily revenue.",
        ["24-hour funding", "No fixed payments", "Bad credit considered"],
        "$10K-$1M",
      ),
      make(
        "short-term-business-loans",
        "Short-Term Business Loans",
        Banknote,
        "Bridge the next 3-18 months",
        "Fixed-term capital for inventory pre-buys, marketing pushes and short-window opportunities.",
        ["3-18 month terms", "Daily or weekly payments", "No prepayment penalty"],
        "Funded same week",
      ),
    ],
  },
];

export function getIndustry(slug: string): Industry | undefined {
  return INDUSTRIES.find((i) => i.slug === slug);
}
