/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AustinRouteImport } from './routes/austin'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PillarSlugRouteImport } from './routes/pillar.$slug'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as AustinSuburbRouteImport } from './routes/austin.$suburb'
import { Route as AustinSuburbPillarRouteImport } from './routes/austin.$suburb.$pillar'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinRoute = AustinRouteImport.update({
  id: '/austin',
  path: '/austin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarSlugRoute = PillarSlugRouteImport.update({
  id: '/pillar/$slug',
  path: '/pillar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AustinSuburbRoute = AustinSuburbRouteImport.update({
  id: '/$suburb',
  path: '/$suburb',
  getParentRoute: () => AustinRoute,
} as any)
const AustinSuburbPillarRoute = AustinSuburbPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => AustinSuburbRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/austin': typeof AustinRouteWithChildren
  '/contact': typeof ContactRoute
  '/austin/$suburb': typeof AustinSuburbRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/austin/$suburb/$pillar': typeof AustinSuburbPillarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/austin': typeof AustinRouteWithChildren
  '/contact': typeof ContactRoute
  '/austin/$suburb': typeof AustinSuburbRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/austin/$suburb/$pillar': typeof AustinSuburbPillarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/austin': typeof AustinRouteWithChildren
  '/contact': typeof ContactRoute
  '/austin/$suburb': typeof AustinSuburbRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/austin/$suburb/$pillar': typeof AustinSuburbPillarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-now'
    | '/austin'
    | '/contact'
    | '/austin/$suburb'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/austin/$suburb/$pillar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-now'
    | '/austin'
    | '/contact'
    | '/austin/$suburb'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/austin/$suburb/$pillar'
  id:
    | '__root__'
    | '/'
    | '/apply-now'
    | '/austin'
    | '/contact'
    | '/austin/$suburb'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/austin/$suburb/$pillar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyNowRoute: typeof ApplyNowRoute
  AustinRoute: typeof AustinRouteWithChildren
  ContactRoute: typeof ContactRoute
  IndustrySlugRoute: typeof IndustrySlugRoute
  PillarSlugRoute: typeof PillarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin': {
      id: '/austin'
      path: '/austin'
      fullPath: '/austin'
      preLoaderRoute: typeof AustinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar/$slug': {
      id: '/pillar/$slug'
      path: '/pillar/$slug'
      fullPath: '/pillar/$slug'
      preLoaderRoute: typeof PillarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/austin/$suburb': {
      id: '/austin/$suburb'
      path: '/$suburb'
      fullPath: '/austin/$suburb'
      preLoaderRoute: typeof AustinSuburbRouteImport
      parentRoute: typeof AustinRoute
    }
    '/austin/$suburb/$pillar': {
      id: '/austin/$suburb/$pillar'
      path: '/$pillar'
      fullPath: '/austin/$suburb/$pillar'
      preLoaderRoute: typeof AustinSuburbPillarRouteImport
      parentRoute: typeof AustinSuburbRoute
    }
  }
}

interface AustinSuburbRouteChildren {
  AustinSuburbPillarRoute: typeof AustinSuburbPillarRoute
}

const AustinSuburbRouteChildren: AustinSuburbRouteChildren = {
  AustinSuburbPillarRoute: AustinSuburbPillarRoute,
}

const AustinSuburbRouteWithChildren = AustinSuburbRoute._addFileChildren(
  AustinSuburbRouteChildren,
)

interface AustinRouteChildren {
  AustinSuburbRoute: typeof AustinSuburbRouteWithChildren
}

const AustinRouteChildren: AustinRouteChildren = {
  AustinSuburbRoute: AustinSuburbRouteWithChildren,
}

const AustinRouteWithChildren =
  AustinRoute._addFileChildren(AustinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyNowRoute: ApplyNowRoute,
  AustinRoute: AustinRouteWithChildren,
  ContactRoute: ContactRoute,
  IndustrySlugRoute: IndustrySlugRoute,
  PillarSlugRoute: PillarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
